version: "3"
services:
  backend:
    image: python:3.9
    working_dir: /app
    volumes:
      - ../backend:/app
    command: bash -c "pip install -r requirements.txt && python app.py"
    ports:
      - "3000:3000"

  frontend:
    image: node:16
    working_dir: /app
    volumes:
      - ../frontend:/app
    command: bash -c "npm install && npm start"
    ports:
      - "8080:3000"
    depends_on:
      - backend
